# Generated by Django 4.2 on 2023-07-26 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="api.ad",
            ),
        ),
    ]
